### ISSUE TITLE
cannot find the tracks checkpoint

### ISSUE THREAD

**Issue by LijiaDong1220** [hongluzhou/hrnet_pose_extract#1]
Thanks for your contributions and code!
Under the  "--track_path", cannot find how to install or generate the model parameters of the tracking model?
Hope u return soon..

**Comment by hongluzhou** [comment]
Thank you for your interests! 

`--track_path` is not the path for the tracking model checkpoint; it is the path to the tracked bounding boxes of persons. Regarding how to obtain the tracked bounding boxes, you can search for a tracking method or use even manual annotated ones. 

An example of the file you need to populate `--track_path path_to_tracks_normalized` would be the file 'tracks_normalized.pkl' mentioned in https://github.com/hongluzhou/composer. You can check the expected format of the file in the [DATA_README.txt](https://github.com/hongluzhou/composer/blob/main/DATA_README.txt).

Best,
Honglu

**Comment by LijiaDong1220** [comment]
> Thank you for your interests!
> 
> `--track_path` is not the path for the tracking model checkpoint; it is the path to the tracked bounding boxes of persons. Regarding how to obtain the tracked bounding boxes, you can search for a tracking method or use even manual annotated ones.
> 
> An example of the file you need to populate `--track_path path_to_tracks_normalized` would be the file 'tracks_normalized.pkl' mentioned in https://github.com/hongluzhou/composer. You can check the expected format of the file in the [DATA_README.txt](https://github.com/hongluzhou/composer/blob/main/DATA_README.txt).
> 
> Best, Honglu

Thanks for your reply~~~
